import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { GeneratedDocument, DocType } from '../types';
import { Download, FileText, Printer, Check, Copy, ArrowLeft } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface DocumentPreviewProps {
    doc: GeneratedDocument;
    docType: string;
    onReset: () => void;
}

const DocumentPreview: React.FC<DocumentPreviewProps> = ({ doc, docType, onReset }) => {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(doc.content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handlePrintPDF = () => {
        window.print();
    };

    const handleExportWord = () => {
        const preHtml = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>${doc.title}</title><style>body{font-family: 'Calibri', sans-serif;}</style></head><body>`;
        const postHtml = "</body></html>";
        
        // Convert markdown to a simple HTML representation for Word (naive conversion via DOM)
        const previewElement = document.getElementById('markdown-preview');
        if (!previewElement) return;
        
        const htmlContent = preHtml + previewElement.innerHTML + postHtml;

        const blob = new Blob(['\ufeff', htmlContent], {
            type: 'application/msword'
        });
        
        const url = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(htmlContent);
        
        const downloadLink = document.createElement("a");
        document.body.appendChild(downloadLink);
        
        if (navigator.userAgent.indexOf("Chrome") !== -1) {
             downloadLink.href = window.URL.createObjectURL(blob);
        } else {
            downloadLink.href = url;
        }
        
        downloadLink.download = `${doc.title.replace(/\s+/g, '_')}.doc`;
        downloadLink.click();
        document.body.removeChild(downloadLink);
    };

    return (
        <div className="max-w-5xl mx-auto px-4 py-8 w-full">
            {/* Toolbar */}
            <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4 print:hidden">
                <div className="flex items-center gap-4">
                    <button 
                        onClick={onReset}
                        className="p-2 hover:bg-slate-100 rounded-lg text-slate-500 transition-colors"
                        title="Back to Dashboard"
                    >
                        <ArrowLeft className="w-5 h-5" />
                    </button>
                    <div>
                        <h1 className="text-2xl font-bold text-slate-900">{doc.title}</h1>
                        <p className="text-sm text-slate-500">Generated by AnalystAlly</p>
                    </div>
                </div>
                
                <div className="flex flex-wrap gap-2">
                    <button 
                        onClick={handleCopy}
                        className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 hover:border-slate-300 transition-all font-medium text-sm shadow-sm"
                    >
                        {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                        {copied ? 'Copied' : 'Copy Text'}
                    </button>
                    <button 
                        onClick={handlePrintPDF}
                        className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 hover:border-slate-300 transition-all font-medium text-sm shadow-sm"
                    >
                        <Printer className="w-4 h-4" />
                        Print / Save PDF
                    </button>
                    <button 
                        onClick={handleExportWord}
                        className="flex items-center gap-2 px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-all font-medium text-sm shadow-md shadow-primary/20"
                    >
                        <FileText className="w-4 h-4" />
                        Export to Word
                    </button>
                </div>
            </div>

            {/* Document View */}
            <div className="bg-white shadow-lg rounded-none md:rounded-xl border border-slate-200 min-h-[29.7cm] p-8 md:p-16 print:shadow-none print:border-none print:p-0 print:w-full">
                <div id="markdown-preview" className="markdown-body font-serif text-lg leading-relaxed max-w-[21cm] mx-auto">
                    <ReactMarkdown>{doc.content}</ReactMarkdown>
                </div>
            </div>
            
            <style>{`
                @media print {
                    body * {
                        visibility: hidden;
                    }
                    .bg-white, .bg-white * {
                        visibility: visible;
                    }
                    .bg-white {
                        position: absolute;
                        left: 0;
                        top: 0;
                        width: 100%;
                        margin: 0;
                        padding: 20px;
                        box-shadow: none;
                        border: none;
                    }
                    @page {
                        size: auto;
                        margin: 20mm;
                    }
                }
            `}</style>
        </div>
    );
};

export default DocumentPreview;