
import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { GeneratedDocument } from '../types';
import { FileText, Printer, Check, Copy, ArrowLeft, Save, Edit3 } from 'lucide-react';
import ExportModal from './ExportModal';

interface DocumentPreviewProps {
    doc: GeneratedDocument;
    docType: string;
    onBack: () => void;
    onSave: () => void;
    onEditResponses: () => void;
    version?: number;
    lastUpdated?: Date;
}

const DocumentPreview: React.FC<DocumentPreviewProps> = ({ 
    doc, 
    docType, 
    onBack, 
    onSave, 
    onEditResponses,
    version,
    lastUpdated 
}) => {
    const [copied, setCopied] = useState(false);
    const [showExportModal, setShowExportModal] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(doc.content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handlePrintPDF = () => {
        window.print();
    };

    const handleExportWord = () => {
        const preHtml = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>${doc.title}</title><style>body{font-family: 'Calibri', sans-serif;}</style></head><body>`;
        const postHtml = "</body></html>";
        
        const previewElement = document.getElementById('markdown-preview');
        if (!previewElement) return;
        
        const htmlContent = preHtml + previewElement.innerHTML + postHtml;

        const blob = new Blob(['\ufeff', htmlContent], {
            type: 'application/msword'
        });
        
        const url = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(htmlContent);
        
        const downloadLink = document.createElement("a");
        document.body.appendChild(downloadLink);
        
        if (navigator.userAgent.indexOf("Chrome") !== -1) {
             downloadLink.href = window.URL.createObjectURL(blob);
        } else {
            downloadLink.href = url;
        }
        
        downloadLink.download = `${doc.title.replace(/\s+/g, '_')}.doc`;
        downloadLink.click();
        document.body.removeChild(downloadLink);
    };

    const handleExportAction = (format: 'word' | 'pdf') => {
        if (format === 'word') {
            handleExportWord();
        } else {
            handlePrintPDF();
        }
        setShowExportModal(false);
    };

    return (
        <div className="max-w-5xl mx-auto px-4 py-8 w-full">
             <ExportModal 
                isOpen={showExportModal}
                onClose={() => setShowExportModal(false)}
                onExport={handleExportAction}
            />

            {/* Toolbar */}
            <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4 print:hidden animate-in slide-in-from-top duration-500">
                <div className="flex items-center gap-4">
                    <button 
                        onClick={onBack}
                        className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 transition-colors"
                        title="Back"
                    >
                        <ArrowLeft className="w-5 h-5" />
                    </button>
                    <div>
                        <h1 className="text-2xl font-bold text-white">{doc.title}</h1>
                        <p className="text-sm text-slate-400 flex items-center gap-2">
                            Generated by AnalystPro <span className="w-1 h-1 rounded-full bg-slate-600"></span> {version ? `v${version}` : 'Draft'}
                        </p>
                    </div>
                </div>
                
                <div className="flex flex-wrap gap-2">
                    <button 
                        onClick={onEditResponses}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-800 border border-slate-700 text-slate-300 rounded-lg hover:bg-slate-700 transition-all font-medium text-sm shadow-sm"
                    >
                        <Edit3 className="w-4 h-4" />
                        Edit Responses
                    </button>

                    <div className="w-px h-8 bg-slate-700 mx-1 hidden md:block"></div>

                    <button 
                        onClick={handleCopy}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-800 border border-slate-700 text-slate-300 rounded-lg hover:bg-slate-700 transition-all font-medium text-sm shadow-sm"
                    >
                        {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                        {copied ? 'Copied' : 'Copy'}
                    </button>
                    
                    <button 
                        onClick={() => setShowExportModal(true)}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-800 border border-slate-700 text-slate-300 rounded-lg hover:bg-slate-700 transition-all font-medium text-sm shadow-sm"
                    >
                        <FileText className="w-4 h-4" />
                        Export
                    </button>

                    <button 
                        onClick={onSave}
                        className="flex items-center gap-2 px-6 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-all font-medium text-sm shadow-lg shadow-primary/20 animate-pulse hover:animate-none"
                    >
                        <Save className="w-4 h-4" />
                        {version ? 'Save Changes' : 'Save to Project'}
                    </button>
                </div>
            </div>

            {/* Document View */}
            <div className="bg-white shadow-2xl shadow-black/50 rounded-none md:rounded-xl min-h-[29.7cm] p-8 md:p-16 print:shadow-none print:p-0 print:w-full overflow-hidden relative">
                <div id="markdown-preview" className="markdown-body font-serif text-lg leading-relaxed max-w-[21cm] mx-auto text-slate-900 pb-16">
                    <ReactMarkdown>{doc.content}</ReactMarkdown>
                </div>
                
                {/* Footer Metadata (Visible on print/export usually, but styled here for UI) */}
                <div className="absolute bottom-0 left-0 w-full bg-slate-50 border-t border-slate-100 p-4 text-center text-xs text-slate-400 font-sans flex justify-between px-16 print:hidden">
                    <span>Doc: {docType}</span>
                    <span>Version: {version || 1}.0 &bull; Updated: {lastUpdated ? lastUpdated.toLocaleDateString() + ' ' + lastUpdated.toLocaleTimeString() : new Date().toLocaleDateString()}</span>
                </div>
            </div>
            
            <style>{`
                @media print {
                    body * {
                        visibility: hidden;
                    }
                    .bg-white, .bg-white * {
                        visibility: visible;
                    }
                    .bg-white {
                        position: absolute;
                        left: 0;
                        top: 0;
                        width: 100%;
                        margin: 0;
                        padding: 20px;
                        box-shadow: none;
                        border: none;
                    }
                    @page {
                        size: auto;
                        margin: 20mm;
                    }
                }
            `}</style>
        </div>
    );
};

export default DocumentPreview;
